/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import banco.BancoDados;
import java.awt.event.KeyEvent;
import java.io.File;
import java.nio.file.Files;
import java.security.PrivateKey;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.LicencaModel;
import util.RSAUtil;

/**
 *
 * @author Maxwell
 */
public class LicencaInternalFrame extends javax.swing.JInternalFrame {

    private BancoDados bd;
    private PrivateKey chavePrivada;

    /**
     * Creates new form LicencaInternalFrame
     * @param bd
     * @param chavePrivada
     */
    public LicencaInternalFrame(BancoDados bd, PrivateKey chavePrivada) {
        initComponents();
        this.bd = bd;
        this.chavePrivada = chavePrivada;

    }//Construtor

    private void gerarLicenca() {
        try {
            // Valida campos obrigatórios
            if (txtNome.getText().trim().isEmpty()
                    || txtEmail.getText().trim().isEmpty()
                    || txtHwId.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "PREENCHA NOME, E-MAIL E HARDWARE ID!");
                return;
            }

            // Monta o modelo
            LicencaModel lic = new LicencaModel();
            lic.setNome(txtNome.getText().trim());
            lic.setEmail(txtEmail.getText().trim());
            lic.setHardwareId(txtHwId.getText().trim());
            lic.setProduto(txtProduto.getText().trim());
            lic.setValidade(txtValidade.getText().trim());
            lic.setGeradaEm(LocalDateTime.now()
                    .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));

            // Assina com RSA
            String assinatura = RSAUtil.assinar(
                    lic.getConteudoParaAssinar(), chavePrivada);
            lic.setAssinatura(assinatura);

            // Mostra preview na área de texto
            txtLicenca.setText(lic.getConteudoArquivo());

            // Salva no banco
            bd.salvarLicenca(lic);

            // Pergunta onde salvar o arquivo .lic
            JFileChooser fc = new JFileChooser();
            fc.setSelectedFile(new File(
                    lic.getEmail().replace("@", "_") + ".lic"));
            int resultado = fc.showSaveDialog(this);
            if (resultado == JFileChooser.APPROVE_OPTION) {
                Files.write(fc.getSelectedFile().toPath(),
                        lic.getConteudoArquivo().getBytes("UTF-8"));
                JOptionPane.showMessageDialog(this,
                        "LICENÇA GERADA E SALVA!\n"
                        + "ENVIE O ARQUIVO .lic AO CLIENTE.");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "ERRO AO GERAR LICENÇA: " + ex.getMessage());
        }
    }//gerarLicenca

    private void limparCampos() {
        txtNome.setText("");
        txtEmail.setText("");
        txtHwId.setText("");
        txtProduto.setText("");
        txtValidade.setText("");
        txtLicenca.setText("");
        txtNome.requestFocus(); // coloca o cursor no primeiro campo
    }//limparCampos

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLicenca = new javax.swing.JPanel();
        btnLimparCampos = new javax.swing.JButton();
        btnGerarSalvarLicenca = new javax.swing.JButton();
        panelDadosCliente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        panelProduto = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValidade = new javax.swing.JTextField();
        panelHwId = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtHwId = new javax.swing.JTextField();
        panelPreview = new javax.swing.JPanel();
        scrollLicenca = new javax.swing.JScrollPane();
        txtLicenca = new javax.swing.JTextArea();
        btnFechar = new javax.swing.JButton();

        setBorder(null);
        setFrameIcon(null);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        panelLicenca.setBackground(new java.awt.Color(255, 255, 255));
        panelLicenca.setPreferredSize(new java.awt.Dimension(1000, 666));
        panelLicenca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimparCampos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnLimparCampos.setText("LIMPAR");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });
        panelLicenca.add(btnLimparCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 180, 35));

        btnGerarSalvarLicenca.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnGerarSalvarLicenca.setText("GERAR E SALVAR LICENÇA");
        btnGerarSalvarLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarSalvarLicencaActionPerformed(evt);
            }
        });
        panelLicenca.add(btnGerarSalvarLicenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 230, 35));

        panelDadosCliente.setBackground(new java.awt.Color(255, 255, 255));
        panelDadosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N
        panelDadosCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("NOME *");
        panelDadosCliente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNometxtHWID(evt);
            }
        });
        panelDadosCliente.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 480, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("E-MAIL *");
        panelDadosCliente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, 30));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailtxtHWID(evt);
            }
        });
        panelDadosCliente.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 390, 30));

        panelLicenca.add(panelDadosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 940, 100));

        panelProduto.setBackground(new java.awt.Color(255, 255, 255));
        panelProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto e prazo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N
        panelProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("PRODUTO");
        panelProduto.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 30));

        txtProduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProdutoKeyPressed(evt);
            }
        });
        panelProduto.add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 570, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("VALIDADE");
        panelProduto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 150, 30));

        txtValidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtValidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValidadeKeyPressed(evt);
            }
        });
        panelProduto.add(txtValidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 300, 30));

        panelLicenca.add(panelProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 940, 100));

        panelHwId.setBackground(new java.awt.Color(255, 255, 255));
        panelHwId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hardware recebido por e-mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N
        panelHwId.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("HWID");
        panelHwId.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 30));

        txtHwId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelHwId.add(txtHwId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 900, 30));

        panelLicenca.add(panelHwId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 940, 100));

        panelPreview.setBackground(new java.awt.Color(255, 255, 255));
        panelPreview.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preview da Licença gerada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N
        panelPreview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLicenca.setColumns(20);
        txtLicenca.setRows(5);
        scrollLicenca.setViewportView(txtLicenca);

        panelPreview.add(scrollLicenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 900, 110));

        panelLicenca.add(panelPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 940, 160));

        btnFechar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnFechar.setText("FECHAR");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        panelLicenca.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, 150, 35));

        getContentPane().add(panelLicenca);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNometxtHWID(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNometxtHWID
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtEmail.requestFocus();
        }        
    }//GEN-LAST:event_txtNometxtHWID

    private void txtEmailtxtHWID(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailtxtHWID
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtProduto.requestFocus();
        }
    }//GEN-LAST:event_txtEmailtxtHWID

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnGerarSalvarLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarSalvarLicencaActionPerformed
        gerarLicenca();
    }//GEN-LAST:event_btnGerarSalvarLicencaActionPerformed

    private void txtProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtValidade.requestFocus();
        }
    }//GEN-LAST:event_txtProdutoKeyPressed

    private void txtValidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValidadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtValidade.requestFocus();
        }
    }//GEN-LAST:event_txtValidadeKeyPressed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.doDefaultCloseAction();
    }//GEN-LAST:event_btnFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGerarSalvarLicenca;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelDadosCliente;
    private javax.swing.JPanel panelHwId;
    private javax.swing.JPanel panelLicenca;
    private javax.swing.JPanel panelPreview;
    private javax.swing.JPanel panelProduto;
    private javax.swing.JScrollPane scrollLicenca;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtHwId;
    public javax.swing.JTextArea txtLicenca;
    public javax.swing.JTextField txtNome;
    public javax.swing.JTextField txtProduto;
    public javax.swing.JTextField txtValidade;
    // End of variables declaration//GEN-END:variables
}
