/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import banco.BancoDados;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maxwell
 */
public class ListarInternalFrame extends javax.swing.JInternalFrame {

    private BancoDados bd;
    private JTable tabela;
    private DefaultTableModel modelo;

    /**
     * Creates new form LicencaInternalFrame
     */
    public ListarInternalFrame() {
        initComponents();
        configurarTabela();
        try {
            bd = new BancoDados();
            carregarDados(null); // ← carrega os dados ao abrir
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao conectar ao banco: " + e.getMessage());
        }

    }//Construtor

    private void configurarTabela() {
        // Cria o modelo com as colunas
        modelo = new DefaultTableModel(
                new String[]{"ID", "Nome", "E-mail", "Produto", "Validade", "Ativa"},
                0 // começa com 0 linhas
        ) {
            // Impede o usuário de editar as células clicando
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Aplica o modelo na sua JTable existente
        tblListarLicencas.setModel(modelo);

        // Ajusta largura das colunas
        tblListarLicencas.getColumnModel().getColumn(0).setPreferredWidth(40);  // ID
        tblListarLicencas.getColumnModel().getColumn(1).setPreferredWidth(150); // Nome
        tblListarLicencas.getColumnModel().getColumn(2).setPreferredWidth(180); // E-mail
        tblListarLicencas.getColumnModel().getColumn(3).setPreferredWidth(100); // Produto
        tblListarLicencas.getColumnModel().getColumn(4).setPreferredWidth(80);  // Validade
        tblListarLicencas.getColumnModel().getColumn(5).setPreferredWidth(50);  // Ativa
    }//configurarTabela

    private void carregarDados(String emailFiltro) {
        try {
            modelo.setRowCount(0);
            ResultSet rs = (emailFiltro == null || emailFiltro.isEmpty())
                    ? bd.listarLicencas()
                    : bd.buscarPorEmail(emailFiltro);
            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("nome"),
                    rs.getString("email"),
                    rs.getString("produto"),
                    rs.getString("validade"),
                    rs.getInt("ativa") == 1 ? "Sim" : "Não"
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERRO AO CARREGAR DADOS DA TABELA: " + e.getMessage());
        }
    }//carregarDados

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLicenca = new javax.swing.JPanel();
        btnGerarSalvarLicenca = new javax.swing.JButton();
        btnFecharListar = new javax.swing.JButton();
        panelBuscar = new javax.swing.JPanel();
        txtBusca = new javax.swing.JTextField();
        btnBuscarTodos = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarLicencas = new javax.swing.JTable();
        btnLimparBusca = new javax.swing.JButton();

        setBorder(null);
        setFrameIcon(null);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        panelLicenca.setBackground(new java.awt.Color(255, 255, 255));
        panelLicenca.setPreferredSize(new java.awt.Dimension(1000, 666));
        panelLicenca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGerarSalvarLicenca.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnGerarSalvarLicenca.setText("GERAR E SALVAR LICENÇA");
        btnGerarSalvarLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarSalvarLicencaActionPerformed(evt);
            }
        });
        panelLicenca.add(btnGerarSalvarLicenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 270, 35));

        btnFecharListar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnFecharListar.setText("FECHAR");
        btnFecharListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharListarActionPerformed(evt);
            }
        });
        panelLicenca.add(btnFecharListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, 150, 35));

        panelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        panelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N
        panelBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscatxtHWID(evt);
            }
        });
        panelBuscar.add(txtBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 410, 30));

        btnBuscarTodos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnBuscarTodos.setText("BUSCAR TODOS");
        btnBuscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTodosActionPerformed(evt);
            }
        });
        panelBuscar.add(btnBuscarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 190, 30));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBuscar.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 190, 30));

        panelLicenca.add(panelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 940, 100));

        tblListarLicencas.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tblListarLicencas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "E-mail", "Produto", "Validade", "Ativa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListarLicencas.getTableHeader().setReorderingAllowed(false);
        tblListarLicencas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblListarLicencasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblListarLicencas);

        panelLicenca.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 940, 370));

        btnLimparBusca.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnLimparBusca.setText("LIMPAR");
        btnLimparBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparBuscaActionPerformed(evt);
            }
        });
        panelLicenca.add(btnLimparBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 180, 35));

        getContentPane().add(panelLicenca);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscatxtHWID(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscatxtHWID
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            txtBusca.setText("");
            txtBusca.requestFocus();
            carregarDados(null);
            tblListarLicencas.clearSelection();
        }
    }//GEN-LAST:event_txtBuscatxtHWID

    private void btnBuscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTodosActionPerformed
        txtBusca.setText("");
        carregarDados(null);
    }//GEN-LAST:event_btnBuscarTodosActionPerformed

    private void btnGerarSalvarLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarSalvarLicencaActionPerformed

    }//GEN-LAST:event_btnGerarSalvarLicencaActionPerformed

    private void btnFecharListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharListarActionPerformed
        this.doDefaultCloseAction();
    }//GEN-LAST:event_btnFecharListarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        carregarDados(txtBusca.getText().trim());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimparBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparBuscaActionPerformed
        txtBusca.setText("");       // limpa o campo de busca
        txtBusca.requestFocus();    // coloca o cursor no campo
        carregarDados(null);
        tblListarLicencas.clearSelection();
    }//GEN-LAST:event_btnLimparBuscaActionPerformed

    private void tblListarLicencasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblListarLicencasKeyPressed
         if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            carregarDados(null);
            tblListarLicencas.clearSelection();
        }
    }//GEN-LAST:event_tblListarLicencasKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarTodos;
    private javax.swing.JButton btnFecharListar;
    private javax.swing.JButton btnGerarSalvarLicenca;
    private javax.swing.JButton btnLimparBusca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelLicenca;
    private javax.swing.JTable tblListarLicencas;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
