/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import banco.BancoDados;
import banco.BancoUsuarios;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Maxwell
 */
public class LoginUI extends javax.swing.JFrame {

    private BancoUsuarios bancoUsuarios;
    private BancoDados bancoDados;
    
//    GeradorLicencaUI principal = new GeradorLicencaUI(banco,login);
    /**
     * Creates new form Login
     *
     * @param bancoUsuarios
     * @param bancoDados
     */
    public LoginUI(BancoUsuarios bancoUsuarios,BancoDados bancoDados) {
        initComponents();
        this.bancoUsuarios = bancoUsuarios;
        this.bancoDados = bancoDados;
        //Imagem do software
        ImageIcon iconUCKG = new ImageIcon(this.getClass().getClassLoader().getResource("img/UltraCipaKEY.png"));
        this.setIconImage(iconUCKG.getImage());
        txtEmail.requestFocus();
    }//construtor

    private void logar() {
        String email = txtEmail.getText().trim().toLowerCase();
        char[] senha = txtSenha.getPassword();
        String password = new String(senha);

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO E-MAIL.");
            txtEmail.requestFocus();
            return;
        }

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO SENHA.");
            txtSenha.requestFocus();
            return;
        }

        if (!email.isEmpty() && !password.isEmpty()) {

            if (bancoUsuarios.buscarUsuarioPorEmail(email, password)) {
                GeradorLicencaUI principal = new GeradorLicencaUI(bancoUsuarios, bancoDados, this);
                principal.setVisible(true);
                txtEmail.setText("");
                txtSenha.setText("");
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "USUÁRIO OU SENHA INVÁLIDO OU INATIVO PARA ACESSO.");
                txtEmail.setText("");
                txtSenha.setText("");
                txtEmail.requestFocus();
            }
        }//if de acesso ao sistema
    }//logar

    private void limpar() {
        txtEmail.setText("");
        txtSenha.setText("");
        char[] senha = txtSenha.getPassword();
        String password = new String(senha);
        Arrays.fill(senha, '0');
        txtEmail.requestFocus();
    }//limpar

    private void acessarAcessoRestrito() {
        String email = txtEmail.getText().trim();
        char[] senha = txtSenha.getPassword();
        String password = new String(senha);

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO E-MAIL.");
            txtEmail.requestFocus();
            return;
        }

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO SENHA.");
            txtSenha.requestFocus();
            return;
        }

        if (!email.isEmpty() && !password.isEmpty()) {
            if (bancoUsuarios.acessarTelaRestrita(email, password)) {
                CadastroUsuarioUI cu = new CadastroUsuarioUI(this, bancoUsuarios);
                cu.setVisible(true);
                txtEmail.setText("");
                txtSenha.setText("");
            } else {
                txtEmail.setText("");
                txtEmail.requestFocus();
                txtSenha.setText("");
                JOptionPane.showMessageDialog(null, "ACESSO NEGADO.");
            }
        }
    }//acessarAcessoRestrito

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnLogar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        panelPrincipal.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 420, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("E-mail");
        panelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Senha");
        panelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ativar-21.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 140, 40));

        btnLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-saida-renúncia-21.png"))); // NOI18N
        btnLogar.setText("LOGAR");
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 130, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("© 2026 UltraCipaKeyGenerator - Todos os direitos reservados.");
        panelPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 470, -1));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-limpar-aqruivo-21.png"))); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 140, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-chave-21.png"))); // NOI18N
        panelPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-usuario-circulo-21.png"))); // NOI18N
        panelPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UltraCipaKEY.png"))); // NOI18N
        jButton1.setToolTipText("CLIQUE AQUI PARA CADASTRAR NOVOS USUÁRIOS.");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));
        panelPrincipal.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 420, 35));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("LOGIN");
        panelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        getContentPane().add(panelPrincipal);

        setSize(new java.awt.Dimension(600, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        logar();
    }//GEN-LAST:event_btnLogarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        acessarAcessoRestrito();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtSenha.requestFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLogar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
